let config = {
    /*------------
        活动接口
    -------------*/
    app:{
        modelName:"ApiOchirly",
        verbs:{
            sodaStart:{
                get:[],
                post:[]
            },
            sodaEditImg:{
                get:[],
                post:['img']
            },
            sodaAddPoint:{
                get:[],
                post:['pid']
            },
            sodaGetSubmissionByPid:{
                get:[],
                post:['pid']
            },
            sodaGetRank:{
                get:[],
                post:['pid']
            },
            sodaMember:{
                get:[],
                post:['tel','authCode','name','address','phone','section']
            },
            sendCode:{
                get:[],
                post:['tel']
            },
            sodaUpdateInfo:{
                get:[],
                post:['name','address','phone','section']
            },
        }
    },
    /*------------
        统计接口
    -------------*/
    stat:{
        modelName:"ApiCustomizeform",
        verbs:{
            addSubmission:{
                get:['fid'],
                post:['type','detail']
            }
        }
    },
    /*------------
        微信API
    -------------*/
    wechat:{
        modelName:"ApiPublic",
        verbs:{
            getOchirlyJSApiConfig:{
                get:[],
                post:['url']
            },
            getJSApiConfig:{
                get:[],
                post:['url']
            },
            uploadImgBase64:{
                get:[],
                post:['module_type','fileupload','filetype']
            }
        }
    },
    /*------------
        授权API
    -------------*/
    auth:{
        modelName:"ApiOchirly",
        verbs:{
            getOchirlyOauthCode:{
                get:['target'],
                post:[]
            },
            getOchirlyOpenIDInfoWithCode:{
                get:[],
                post:['code','openidname']
            }
        }
    }
};

module.exports = config;